import '../css/style.css';
import '../css/subtable_split.css';
import './module/yubinkensaku.js';
import './module/disable.js';
import './module/hidden.js';
import './module/age.js';
import './module/CheckCopy.js';
import './module/FamilyChecker.js';
import './module/subtable_split.js';
