import '../css/EMCloud_common.css';
import '../css/style.css';
import './module/config.js';
import './module/common';
import './module/age_calculator.js';
import './module/undeletable.js';
import './module/CheckCopy.js';
import './module/EMC2_appCoordination.js';
import './module/yubinkensaku.js';
